### ISSUE TITLE
Come up with a better name for cryptocheck

### ISSUE THREAD

**Issue by RSAkidinUSA** [RSAkidinUSA/shellanigans#8]
The name is pretty lame, we need a better one to emphasize the ineffectiveness of this program

**Comment by Owen-E** [comment]
BogoCoin

**Comment by RSAkidinUSA** [comment]
Other suggestions are:
BogoExchange
BogoCrypt
CryptBogo

**Comment by RSAkidinUSA** [comment]
[Reference](https://en.wikipedia.org/wiki/Bogosort)

**Comment by RSAkidinUSA** [comment]
I'm going with bogoexchange unless anyone has a better name
